chore: update ci workflow and fix lint errors
affects: @gio-design/components

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,26 +13,6 @@ jobs:
           fetch-depth: 2
       - run: git checkout HEAD^2
         if: ${{ github.event_name == 'pull_request' }}
-  lint:
-    name: Lint Checks
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: '1'
-      - name: Lint commits count
-        if: ${{ github.event.pull_request.commits > 3 }}
-        run: echo "::error the commits of pull request should not be more than 3"
-      - name: Lint codes
-        uses: github/super-linter@v3
-        env:
-          CSS_FILE_NAME: stylelint.config.js
-          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.js
-          VALIDATE_JAVASCRIPT_STANDARD: false
-          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.js
-          VALIDATE_TYPESCRIPT_STANDARD: false
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   install:
     name: Install dependencies
     runs-on: ubuntu-latest
@@ -55,6 +35,35 @@ jobs:
       - name: Bootstrap
         if: steps.cache-node-modules.outputs.cache-hit != 'true'
         run: yarn bootstrap
+  lint:
+    name: Lint Checks
+    needs: install
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: '1'
+      - name: Setup Node.js
+        uses: actions/setup-node@v2.1.1
+        with:
+          node-version: 12.x
+      - name: Restore Node.js modules
+        uses: actions/cache@v2
+        with:
+          path: |
+            node_modules
+            */*/node_modules
+          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
+      - name: Lint pull request title
+        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
+      - name: Lint commits count
+        if: ${{ github.event.pull_request.commits > 3 }}
+        run: echo "::error::The commits of pull request should not be more than 3 && exit 1"
+      - name: StyleLint
+        run: yarn lint:style
+      - name: ESLint
+        run: yarn lint:components
   build:
     name: Build Packages
     needs: install
